"""convert status to enum

Revision ID: d3454901e315
Revises: d7e1f16c2136
Create Date: 2026-03-16 16:52:04.876062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3454901e315'
down_revision: Union[str, Sequence[str], None] = 'd7e1f16c2136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    order_status_enum = sa.Enum(
    'CREATED',
    'PAID',
    'SHIPPED',
    'DELIVERED',
    'CANCELLED',
    name='order_status_enum'
)
    order_status_enum.create(bind, checkfirst=True)

    payment_status_enum = sa.Enum(
        'PENDING',
        'PROCESSING',
        'SUCCESS',
        'FAILED',
        'REFUNDED',
        name='payment_status_enum'
    )
    payment_status_enum.create(bind, checkfirst=True)

    shipment_status_enum = sa.Enum(
        'CREATED',
        'SHIPPED',
        'OUT_FOR_DELIVERY',
        'DELIVERED',
        name='shipment_status_enum'
    )
    shipment_status_enum.create(bind, checkfirst=True)
    shipment_tracking_status_enum = sa.Enum(
    'CREATED',
    'PICKED_UP',
    'IN_TRANSIT',
    'ARRIVED_AT_HUB',
    'OUT_FOR_DELIVERY',
    'DELIVERED',
    'FAILED_DELIVERY',
    name='shipment_tracking_status_enum'
)

    shipment_tracking_status_enum.create(bind, checkfirst=True)

    # -------- ALTER COLUMNS --------

    op.alter_column(
        'orders',
        'order_status',
        existing_type=sa.VARCHAR(),
        type_=order_status_enum,
        postgresql_using="order_status::order_status_enum",
        nullable=False
    )

    op.alter_column(
        'payments',
        'payment_status',
        existing_type=sa.VARCHAR(),
        type_=payment_status_enum,
        postgresql_using="payment_status::payment_status_enum",
        nullable=False
    )

    op.alter_column(
        'shipments',
        'shipment_status',
        existing_type=sa.VARCHAR(),
        type_=shipment_status_enum,
        postgresql_using="shipment_status::shipment_status_enum",
        nullable=False
    )
    op.alter_column(
    'shipment_tracking',
    'status',
    existing_type=sa.VARCHAR(),
    type_=shipment_tracking_status_enum,
    postgresql_using="status::shipment_tracking_status_enum"
)

def downgrade() -> None:
    bind = op.get_bind()

    order_status_enum = sa.Enum(name='order_status_enum')
    payment_status_enum = sa.Enum(name='payment_status_enum')
    shipment_status_enum = sa.Enum(name='shipment_status_enum')
    shipment_tracking_status_enum = sa.Enum(name='shipment_tracking_status_enum')

    # revert columns
    op.alter_column(
        'shipment_tracking',
        'status',
        existing_type=shipment_tracking_status_enum,
        type_=sa.VARCHAR(),
        nullable=False
    )

    op.alter_column(
        'shipments',
        'shipment_status',
        existing_type=shipment_status_enum,
        type_=sa.VARCHAR(),
        nullable=False
    )

    op.alter_column(
        'payments',
        'payment_status',
        existing_type=payment_status_enum,
        type_=sa.VARCHAR(),
        nullable=False
    )

    op.alter_column(
        'orders',
        'order_status',
        existing_type=order_status_enum,
        type_=sa.VARCHAR(),
        nullable=False
    )

    # drop enums (reverse order)
    shipment_tracking_status_enum.drop(bind, checkfirst=True)
    shipment_status_enum.drop(bind, checkfirst=True)
    payment_status_enum.drop(bind, checkfirst=True)
    order_status_enum.drop(bind, checkfirst=True)