"""add coupon reference to orders

Revision ID: ee7c048d3f5a
Revises: 5bda7defb240
Create Date: 2026-03-18 11:12:09.169553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7c048d3f5a'
down_revision: Union[str, Sequence[str], None] = '5bda7defb240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_coupon_user', 'coupon_usage', ['coupon_id', 'user_id'], unique=False)
    op.create_unique_constraint('uq_coupon_usage_order', 'coupon_usage', ['order_id'])
    op.add_column('orders', sa.Column('coupon_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_orders_coupon",
        "orders",
        "coupons",
        ["coupon_id"],
        ["id"],
        ondelete="SET NULL"
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_orders_coupon", "orders", type_="foreignkey")
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'coupon_id')
    op.drop_constraint('uq_coupon_usage_order', 'coupon_usage', type_='unique')
    op.drop_index('idx_coupon_user', table_name='coupon_usage')
    # ### end Alembic commands ###
